# configuração do token
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000

#  configuração do banco de dados
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory_database
    username: admin
    password: root

#  configuração JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: false

# configuração swagger
  springdoc:
    pathsToMatch: /person/**
    swagger-ui:
      user-toot-path: true