# Configuração do token JWT
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

# Configuração do banco de dados
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory_database
    username: postgres
    password: root

  # Configuração JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL81Dialect
    show-sql: true

  # Configuração Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true

  # Configuração Swagger
  springdoc:
    pathsToMatch: /person/**
    swagger-ui:
      user-toot-path: true
